<a href="https://colab.research.google.com/github/Vaibhav15012000/KBC-PROJECT/blob/master/NUMPY__TRAINING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a = np.array([10,20,30,40,50,60])


In [ ]:
a=np.zeros((2,3))

b=np.ones((2,3))

In [ ]:
np.random.random(5)

array([0.40633935, 0.32207573, 0.96999476, 0.81883946, 0.44256332])

In [ ]:
np.ones((3,3 , 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
c=np.full(shape=(3,3),fill_value=3)


In [ ]:
c

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [ ]:
np.random.random((3,3))

array([[0.87901281, 0.01734997, 0.32580823],
       [0.80916776, 0.04097154, 0.21514726],
       [0.95762453, 0.88106042, 0.89347106]])

In [ ]:
a=np.arange(100).reshape(20,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
var=np.eye(4)

In [ ]:
var

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
var.dtype

dtype('float64')

In [ ]:
c=np.full(shape=(3, 5) ,fill_value= 5)

In [ ]:
c


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
c.ndim

2

In [ ]:
x=np.random.randint(10, size=(4,4))

In [ ]:
x**2

array([[25, 16,  9,  9],
       [ 9, 64,  4,  1],
       [ 1, 36,  1,  4],
       [25, 16, 16, 16]])

In [ ]:
x*2


array([[10,  8,  6,  6],
       [ 6, 16,  4,  2],
       [ 2, 12,  2,  4],
       [10,  8,  8,  8]])

In [ ]:
x-2

array([[ 3,  2,  1,  1],
       [ 1,  6,  0, -1],
       [-1,  4, -1,  0],
       [ 3,  2,  2,  2]])

Slicing of array



In [ ]:
x[:]

array([[5, 4, 3, 3],
       [3, 8, 2, 1],
       [1, 6, 1, 2],
       [5, 4, 4, 4]])

In [ ]:
x[0:0:1]

array([], shape=(0, 4), dtype=int64)

In [ ]:
x[0:0]

array([], shape=(0, 4), dtype=int64)

In [ ]:
x[0:4]

array([[5, 4, 3, 3],
       [3, 8, 2, 1],
       [1, 6, 1, 2],
       [5, 4, 4, 4]])

In [ ]:
x[-1:]

array([[5, 4, 4, 4]])

In [162]:
b[0:2,1]   #Select items at rows 0 and 1 in column 1

array([2., 5.])

In [163]:
a[ : :-1]      #Reversed array a


array([3, 2, 1])

Vector Operations:

In [ ]:
a=np.arange(4).reshape(2,2)

In [ ]:
b=np.arange(4).reshape(2,2)

In [ ]:
np.dot(a,b)

array([[ 2,  3],
       [ 6, 11]])

In [ ]:
np.multiply(a,b
          )

array([[0, 1],
       [4, 9]])

In [ ]:
np.nan


nan

In [ ]:
x.size

16

In [ ]:
x.shape

(4, 4)

In [ ]:
x.ndim

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.data


Uninitialized array creation


In [ ]:
np.empty((2,3))  # creating an empty array

array([[4.94e-323, 9.88e-323, 1.48e-322],
       [1.98e-322, 2.47e-322, 2.96e-322]])

In [ ]:
 np.linspace( 1,1,1 )  #evenly sequenced array

array([1.])

In [ ]:
x.sum()

56

In [ ]:
x.min()

1

In [ ]:
x.max()

8

In [ ]:
x.cumsum(axis=0)  # cumulative sum along each row


array([[ 5,  4,  3,  3],
       [ 8, 12,  5,  4],
       [ 9, 18,  6,  6],
       [14, 22, 10, 10]])

In [90]:
x.cumsum(axis=1)  # cumulative sum along each column

array([[ 5,  9, 12, 15],
       [ 3, 11, 13, 14],
       [ 1,  7,  8, 10],
       [ 5,  9, 13, 17]])

In [ ]:
a=np.arange(10).reshape(2,5)

In [ ]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [75]:
np.array_equal(a, b) 

False

In [79]:
q=np.arange(6).reshape(2,3)

In [80]:
w=np.arange(6).reshape(2,3)

In [81]:
np.array_equal(q,w) # compares two arrays 

True

In [91]:
a==b  #element wise comparison

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [85]:
m=np.array([1,2,3])
np.exp(m)            #Exponentiation


array([ 2.71828183,  7.3890561 , 20.08553692])

In [92]:
a<2               #element wise comparison


array([[ True,  True, False, False, False],
       [False, False, False, False, False]])

In [86]:
np.sqrt(m)       # Square root


array([1.        , 1.41421356, 1.73205081])

In [87]:
np.sin(m)        #Print sines of an array


array([0.84147098, 0.90929743, 0.14112001])

In [88]:
np.cos(m)        #Element-wise cosine


array([ 0.54030231, -0.41614684, -0.9899925 ])

In [89]:
np.log(m)        # log for all values

array([0.        , 0.69314718, 1.09861229])

In [93]:
a.mean()

4.5

In [97]:
b=np.array([1,2,3,4,5])
np.median(b)                # median is available as a function in numpy****

3.0

In [98]:
b.max()

5

In [99]:
b.min()

1

In [103]:
z=b.std()   # standard deviation

In [104]:
z


1.4142135623730951

In [105]:
z**(1/2)

1.189207115002721

In [106]:
h=a.view()   # view array in another variable

In [107]:
h


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
v=a.copy() # copy array to another variable(deep copy)

In [109]:
v


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
np.copy(a)   #temporary copying of array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
a.sort()

In [112]:
a


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
k=a.transpose()

In [123]:
k

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [124]:
k.T

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [126]:
a.ravel()  #flattens our array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Adding/Removing Elements

In [134]:
np.insert(a,0,5)

array([5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.append(a,b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5])

In [137]:
np.delete(a, [5])

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

Combining Arrays

In [143]:
a=np.array([1,2,3])

In [144]:
b=np.array([1,2,3])

In [146]:
np.concatenate((a,b))

array([1, 2, 3, 1, 2, 3])

Splitting Arrays


In [147]:
np.hsplit(a,3)   #horizontal split

[array([1]), array([2]), array([3])]

In [152]:
b = np.array([(1.5,2,3), (4,5,6)])

In [153]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [159]:
np.vsplit(b,2)

[array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]

Subsetting

In [160]:
a[2]

3

In [161]:
b[1,2]

6.0